language: ruby
jdk:
- oraclejdk8
sudo: false
rvm:
- 2.3.1
before_install:
- openssl aes-256-cbc -K $encrypted_ae88e5f03e59_key -iv $encrypted_ae88e5f03e59_iv
  -in etc/secrets -out ../secrets.tar -d
- chmod 600 ../release.asc
- gpg --import ../release.asc
install:
- rvm use 2.3.1
- gem install bundler
- bundle install
script: buildr clean package publish_if_tagged
git:
  depth: false
env:
  global:
  - secure: l/p06yH3RqYAH+mglPWBJc0hEGoL7TvmEeMm21I/rsFlogkuI/7cgjSl5B7/S4lYHMCee8D+6T1m5cJ7LWDO0aTT010Cz5mpizHl25uez1O0YehpSPeH/uRWsw23ysbf6uAHtXo241z1P2nppjKKb/+1nFyq+Cq3+lgkmMKFK32SsYlxH39URh83Mqls8rZCHtxhuMlybGIlP9UGsu/nXJnbOCt9noEXLfk8zd77fK2uRY+P8vVTH7p9FyoRpqI7O+3Cb9QyIU/8A+s/w7szt193q7GApcTvh9N37SKhDu9OLLWHge2d83ADDyWyTZjYbUua0VXa4hnxS3QcvM/VBrp5m36FFaQ3wEfAo3SN2Lki8Yp95FvzR+3UDl3n6JytReXuNrJU5rR81kYtOXRspqZqmrIj9UH8ilpNxjBzVhLWjKi3hAPE1igZlKHzq2z2wgP7XgWpnv5y3uidZc9xxHe0dKCR4r0Hw2epZ/iM6aIYALU8OFdIWOm6/RkrX8+8xN9c3IcGmI4EdrbqqcdTsBXTXb1VwT9cZTLlf0CH+Br0OmjmUgVeGSs8In2f5ufuP7lQFjPibkgguQPhxy4YuknJLcTIYrcF0YjHe8eGgmxgxTQx/tuofkB6NZUjT7Hxn7GwKOdkmRfRpDXAskl2RTgneTUkXs/Gz8WpAsoFN7A=
  - secure: FJ31qi7OlBvWrnDRlOo5y7B1/9BtWzvT0OxCEyVnS2LsnWkwsQw5ltR6S3yvhh3NvvSbclwNXj+uOY735jCHyQcep42qDDsPM0fzQv9Zq9E1KmMl5+bBk5rEXfUycc07Eu8AU3TmNEAlgePmeehB9ptw+Gy0fK3a/gkvQ2qnVP7qRIOgbH3rvTbkRobYdR9zf9OLBB5mt28hoT6WAquMifVmwVeWmi8w8blH+BBqFEhK3vX/O6xHq42nQgCA9Tx/2BDRjlwvlrj6xhdnl9YrOWQDslmq9bEp3ktc7dLurCtQ0qcmeDiNWSqAdgxM0+YDXdTPnlyg+ftO3wNqbODYyn0z3bdxfCIJ6OrVQJ3v+pQ6YojkYpFIbb6p27lMbfpZ84PpxagrQLGYTw8w3IR9FT5IjEzJbzGleqtftrgoslkTbOS4OjkP3Fm+9gf97lLbpDKuFprQeGyYBQgTMrlCyecW+M4ZhNZdV2RuDq/fOyJmMJLjjoV0m/o9ciSfCUH2hOsfLav7+iA86N2t65QkV5ztzYiQOI7ZW3gI6Z4Nzu/Ywppn9Bn2doaCp3Pgi6rJtdICMM6UXxtHC5SvMQRWJ4wx1KoB41Ib2omHv00Z0svZCsn2A1NuMQljp6FO85S/tSRtwU+z6B4BCMcT0A6295sYTnFByDKjPcxp4GTUm6s=
  - secure: uyi/pt/gtkVJIXWxnFEH7/WTm9+6hoHVWaKWio0B77fJ1Yps3BmUB8lYbRZL7VmuhyWutTeCLaAToXZkj5l55d4bzZYTgksE24Y6CL/GclEnwVOJwht6Xm4fqyQJDQp4O3MEWjMW08pWAS09/rfa3X9UyHb5UdaGCuoNcSrRtBDnemjLinAtnHkq3rgYmJKP3vI48wXGL+6OBWXgLhsgAXs1/df/+2326zhgm6dUVireI1YO8vBDegM/2TsKZHUhUoidbLhb/QeKTCJSGuXd4FBhsMvmg8jd7SbEZwitB5vox6gNrzpSrni2Xx+2Y/96XALO2PKSj2JT2Nn18HPMtAz3dW7eA2Nez8eeWy8hADWrzG3n6tQOSenPbZKTu/TyhPNCQLCfkT0z/EAtmm+BONzhgCMwhYghaklwbaDNprydC6AAhQLDLbrCkzwQ7qEiu1WhGAZyiHZYTurdw8pR0MDmagLavAxReTRcM4w5+x+wd9WstK09VFgipEB9jns4ztk8BHTRdMrniaH/Fm7XeE/e6PCsfdteK9FRYVmVf4lMspXCI47Yj6WQSyB5UWvitLBir4SIkRwXdjPx1xLXZ0iNg7A6q71fWNhx4ncstb8f+HDsJZGVElCX63yJuI+JfbtmGc5W3mBNHedRceVNyvqSTLCinZylY/WPs0sZg9o=
