repositories:
  remote:
   - https://repo.maven.apache.org/maven2
   - https://stocksoftware.artifactoryonline.com/stocksoftware/public
   - https://stocksoftware.artifactoryonline.com/stocksoftware/oss
   - https://stocksoftware.jfrog.io/stocksoftware/staging

artifacts:
  idea_codestyle: au.com.stocksoftware.idea.codestyle:idea-codestyle:xml:1.14

  jsinterop_annotations: com.google.jsinterop:jsinterop-annotations:jar:1.0.2

  javax_annotation: org.realityforge.javax.annotation:javax.annotation:jar:1.0.1

  guiceyloops: org.realityforge.guiceyloops:guiceyloops:jar:0.102

  javax_json: org.glassfish:javax.json:jar:1.1

  # GWT deps
  gwt_user: com.google.gwt:gwt-user:jar:2.8.2
  gwt_dev: com.google.gwt:gwt-dev:jar:2.8.2
