repositories:
  remote:
   - https://stocksoftware.jfrog.io/stocksoftware/maven2
   - https://repo.maven.apache.org/maven2
   - https://stocksoftware.jfrog.io/stocksoftware/staging

artifacts:
  idea_codestyle: au.com.stocksoftware.idea.codestyle:idea-codestyle:xml:1.14

  jsinterop_annotations: org.realityforge.com.google.jsinterop:jsinterop-annotations:jar:2.8.2-v20191108

  javax_annotation: org.realityforge.javax.annotation:javax.annotation:jar:1.0.1

  guiceyloops: org.realityforge.guiceyloops:guiceyloops:jar:0.106

  javax_json: org.glassfish:javax.json:jar:1.1

  # GWT deps
  gwt_user: org.realityforge.com.google.gwt:gwt-user:jar:2.8.2-v20191108
  gwt_dev: org.realityforge.com.google.gwt:gwt-dev:jar:2.8.2-v20191108

  testng: org.testng:testng:jar:6.11
