repositories:
  remote:
   - https://repo.maven.apache.org/maven2

artifacts:
  jsinterop_annotations: com.google.jsinterop:jsinterop-annotations:jar:2.0.0

  javax_annotation: org.realityforge.javax.annotation:javax.annotation:jar:1.1.1

  guiceyloops: org.realityforge.guiceyloops:guiceyloops:jar:0.113

  javax_json: org.glassfish:javax.json:jar:1.1

  # GWT deps
  gwt_user: org.gwtproject:gwt-user:jar:2.10.0
  gwt_dev: org.gwtproject:gwt-dev:jar:2.10.0

  testng: org.testng:testng:jar:6.11
