package org.realityforge.braincheck;

import java.util.function.Supplier;

/**
 * A place to store utility methods that should not be used outside this package.
 */
@SuppressWarnings( "ConstantConditions" )
final class BrainCheckUtil
{
  private BrainCheckUtil()
  {
  }

  /**
   * Return the string generated by specified supplier.
   * Typically this is used to delay instantiation of an error message until it is required.
   * If the supplier generates an exception then catch it and generate an explanatory message.
   *
   * @param message the string supplier to generate message.
   * @return the string generated by supplier.
   */
  static String safeGetString( final Supplier<String> message )
  {
    assert null != message;
    try
    {
      return message.get();
    }
    catch ( final Throwable t )
    {
      return "Exception generated whilst attempting to get supplied message.\n" + throwableToString( t );
    }
  }

  /**
   * Return string converted to stack trace.
   * This method uses explicit traversal of the throwable to be compatible with GWT.
   *
   * Contrast this with the following code that is not compatible with GWT.
   * <pre>
   * final StringWriter out = new StringWriter();
   * t.printStackTrace( new PrintWriter( out ) );
   * </pre>
   *
   * @param throwable the throwable to convert
   * @return the stack trace.
   */
  static String throwableToString( final Throwable throwable )
  {
    assert null != throwable;
    final var sb = new StringBuilder();
    Throwable t = throwable;
    while ( null != t )
    {
      addCausedByPrefix( sb );
      sb.append( t.toString() );
      for ( final StackTraceElement element : t.getStackTrace() )
      {
        sb.append( "\n  at " ).append( element );
      }
      t = t.getCause();
    }

    return sb.toString();
  }

  private static void addCausedByPrefix( final StringBuilder sb )
  {
    if ( 0 != sb.length() )
    {
      sb.append( "\nCaused by: " );
    }
  }
}
